#define MOUSEKEY_WHEEL_INTERVAL 200
#define ENCODERS_PAD_A { GP12 }
#define ENCODERS_PAD_B { GP11 }
#define ENCODER_RESOLUTION 4
#define JOYSTICK_AXIS_COUNT 2
#define I2C_DRIVER I2CD0
#define I2C1_SDA_PIN GP8
#define I2C1_SCL_PIN GP9

//#define CIRQUE_PINNACLE_TAP_ENABLE true