#define ENCODERS_PAD_A { GP18 }
#define ENCODERS_PAD_B { GP19 }
#define ENCODER_RESOLUTION 4
#define JOYSTICK_AXIS_COUNT 2
#define I2C_DRIVER I2CD0
#define I2C1_SDA_PIN GP20
#define I2C1_SCL_PIN GP21
