#define ENCODERS_PAD_A { GP17 }
#define ENCODERS_PAD_B { GP21 }
#define ENCODER_RESOLUTION 4
#define JOYSTICK_AXIS_COUNT 2
#define MOUSEKEY_MAX_SPEED 2
#define MOUSEKEY_MOVE_DELTA 4
#define ANALOG_JOYSTICK_X_AXIS_PIN 27
#define ANALOG_JOYSTICK_Y_AXIS_PIN 26
#define ANALOG_JOYSTICK_SPEED_REGULATOR 12
#define POINTING_DEVICE_INVERT_X true